"""Add Status to Rents 

Revision ID: 896725585894
Revises: a2065cc83ad6
Create Date: 2024-10-04 01:54:35.025685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896725585894'
down_revision: Union[str, None] = 'a2065cc83ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rents', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rents', 'status')
    # ### end Alembic commands ###
